### PR TITLE
amend exports

### PR DESCRIPTION
**Pull request by sinisterstumble**
export `generateGraphQLString` and `generateContentsFromGraphqlString`

### CODE REVIEW

**Comment by louisscruz** [comment]
Just out of curiosity: what was the motivation for exporting these functions?

**Comment by sinisterstumble** [comment]
@louisscruz for a [vite](https://github.com/vitejs/vite) plugin. To avoid the need to fork the repository for this:

```ts
export const viteGraphQLPlugin = (
  options: GraphQLLoaderPluginOptions = {}
): VitePlugin => ({
  name: 'graphql',
  transform(graphqlString: string, id: string) {
    if ((options.filterRegex ?? /\.graphql$/).test(id)) {
      return {
        code: generateContentsFromGraphqlString(
          graphqlString,
          options.mapDocumentNode
        ),
        map: null
      }
    }

    return
  }
})
```

**Comment by sinisterstumble** [comment]
@louisscruz [unplugin](https://github.com/unjs/unplugin), *unified plugin system for vite, rollup, and webpack*, is another possible option.

**Comment by louisscruz** [comment]
After a lot of internal deliberation over this one, I've decided to allow for these functions to be exposed. Generally, I am not in favor of exposing more than is needed in order to keep future implementation and API changes as simple as possible. But this seems harmless enough. Hopefully this doesn't become some source of regret in the future 😆 .

Merged here https://github.com/luckycatfactory/esbuild-graphql-loader/pull/25 and made available as [v3.7.0](https://www.npmjs.com/package/@luckycatfactory/esbuild-graphql-loader/v/3.7.0).

**Comment by sinisterstumble** [comment]
@louisscruz thank you!

**Pull request closed without merging**
